/**
 * Predefined seed fixtures matching docs/SEED_DATA_AND_DEMO_GUIDE.md
 */

const users = [
  // 1. Platform Master Admin
  {
    name: 'System Administrator',
    email: 'admin@petcare.com',
    phone: '+91 99999 00000',
    password: 'Admin@123',
    role: 'ADMIN',
    isActive: true,
  },
  // 2. Pet Owners
  {
    name: 'Sarah Jenkins',
    email: 'sarah@example.com',
    phone: '+91 98765 43210',
    password: 'Owner@123',
    role: 'PET_OWNER',
    isActive: true,
  },
  {
    name: 'Michael Chang',
    email: 'michael@example.com',
    phone: '+91 98765 43211',
    password: 'Owner@123',
    role: 'PET_OWNER',
    isActive: true,
  },
  // 3. Service Providers
  {
    name: 'Dr. Rahul Sharma',
    email: 'dr.sharma@petcare.com',
    phone: '+91 98230 11223',
    password: 'Provider@123',
    role: 'SERVICE_PROVIDER',
    isActive: true,
    providerProfile: {
      providerType: 'Veterinarian',
      specialization: 'General Pet Care & Surgery',
      experience: 5,
      qualification: 'BVSc & AH, MVSc (Surgery)',
      bio: 'Compassionate veterinarian with over 5 years of clinical surgical experience and preventative veterinary care.',
      location: 'Nagpur',
      approvalStatus: 'Approved',
      rating: 4.9,
    },
  },
  {
    name: 'Dr. Emily Watson',
    email: 'dr.watson@petcare.com',
    phone: '+91 98230 44556',
    password: 'Provider@123',
    role: 'SERVICE_PROVIDER',
    isActive: true,
    providerProfile: {
      providerType: 'Veterinarian',
      specialization: 'Feline Internal Medicine & Canine Wellness',
      experience: 3,
      qualification: 'BVSc & AH',
      bio: 'Dedicated clinical veterinarian with a passion for companion animal preventative health and dietary counseling.',
      location: 'Mumbai',
      approvalStatus: 'Pending', // Pending for admin approval test
      rating: 4.7,
    },
  },
  {
    name: 'Oliver Twist Grooming',
    email: 'oliver@petcare.com',
    phone: '+91 98230 77889',
    password: 'Provider@123',
    role: 'SERVICE_PROVIDER',
    isActive: true,
    providerProfile: {
      providerType: 'Pet Groomer',
      specialization: 'Breed Styling & De-shedding Treatments',
      experience: 4,
      qualification: 'Certified Master Pet Stylist (CMG)',
      bio: 'Specializing in fear-free handling and luxury spa grooming for dogs of all sizes and coat textures.',
      location: 'Mumbai',
      approvalStatus: 'Approved',
      rating: 4.8,
    },
  },
  {
    name: 'Chloe Fluff Studio',
    email: 'chloe@petcare.com',
    phone: '+91 98230 99001',
    password: 'Provider@123',
    role: 'SERVICE_PROVIDER',
    isActive: true,
    providerProfile: {
      providerType: 'Pet Groomer',
      specialization: 'Show Dog Coat Preparation & Cat Grooming',
      experience: 6,
      qualification: 'Professional Grooming Diploma',
      bio: 'Gentle, modern grooming studio focused on stress-free baths, hygiene trims, and aesthetic show styling.',
      location: 'Pune',
      approvalStatus: 'Approved',
      rating: 4.8,
    },
  },
  {
    name: 'Alex Canine Academy',
    email: 'alex@petcare.com',
    phone: '+91 98230 33221',
    password: 'Provider@123',
    role: 'SERVICE_PROVIDER',
    isActive: true,
    providerProfile: {
      providerType: 'Pet Trainer',
      specialization: 'Behavior Modification & Canine Agility',
      experience: 7,
      qualification: 'CPDT-KA Certified Professional Dog Trainer',
      bio: 'Science-based positive reinforcement dog trainer helping owners solve reactive behaviors and build lasting bonds.',
      location: 'Bangalore',
      approvalStatus: 'Approved',
      rating: 4.9,
    },
  },
  {
    name: 'David Paws Training',
    email: 'david@petcare.com',
    phone: '+91 98230 66554',
    password: 'Provider@123',
    role: 'SERVICE_PROVIDER',
    isActive: true,
    providerProfile: {
      providerType: 'Pet Trainer',
      specialization: 'Protection Dog & Working Breeds',
      experience: 4,
      qualification: 'Working Dog Handler Certificate',
      bio: 'Specialized training for guard dogs, boundary awareness, and advanced agility routines.',
      location: 'Delhi',
      approvalStatus: 'Suspended', // Suspended for marketplace exclusion test
      rating: 4.2,
    },
  },
];

// Pets mapping to owner email
const petsData = [
  {
    ownerEmail: 'sarah@example.com',
    name: 'Max',
    species: 'Dog',
    breed: 'Golden Retriever',
    gender: 'Male',
    age: 3,
    weight: 28.5,
    medicalNotes: 'Allergic to chicken proteins. Receives daily omega-3 supplements.',
    vaccinationStatus: 'Up to Date',
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80',
  },
  {
    ownerEmail: 'sarah@example.com',
    name: 'Bella',
    species: 'Cat',
    breed: 'Persian',
    gender: 'Female',
    age: 2,
    weight: 4.2,
    medicalNotes: 'Sensitive digestion; prefers grain-free dry kibble.',
    vaccinationStatus: 'Up to Date',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80',
  },
  {
    ownerEmail: 'michael@example.com',
    name: 'Luna',
    species: 'Rabbit',
    breed: 'Holland Lop',
    gender: 'Female',
    age: 1,
    weight: 1.8,
    medicalNotes: 'Requires timothy hay and fresh greens diet. Sensitive ears.',
    vaccinationStatus: 'Up to Date',
    image: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=600&q=80',
  },
  {
    ownerEmail: 'michael@example.com',
    name: 'Milo',
    species: 'Dog',
    breed: 'French Bulldog',
    gender: 'Male',
    age: 4,
    weight: 12.0,
    medicalNotes: 'Mild brachycephalic breathing syndrome; avoid strenuous heat.',
    vaccinationStatus: 'Up to Date',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=600&q=80',
  },
];

// Services mapping to provider email
const servicesData = [
  // Dr. Rahul Sharma (Veterinarian)
  {
    providerEmail: 'dr.sharma@petcare.com',
    name: 'General Checkup',
    category: 'Veterinary',
    duration: 30,
    price: 500,
    description: 'Physical inspection, heart & lung auscultation, temperature, ear & eye exam.',
    isActive: true,
  },
  {
    providerEmail: 'dr.sharma@petcare.com',
    name: 'Vaccination & Shots',
    category: 'Veterinary',
    duration: 25,
    price: 850,
    description: 'Core immunization for rabies, distemper, parvovirus, and hepatitis.',
    isActive: true,
  },
  {
    providerEmail: 'dr.sharma@petcare.com',
    name: 'Pet Consultation',
    category: 'Veterinary',
    duration: 45,
    price: 600,
    description: 'In-depth nutritional, dietary, or behavioral medical evaluation.',
    isActive: true,
  },
  {
    providerEmail: 'dr.sharma@petcare.com',
    name: 'Dental Checkup',
    category: 'Veterinary',
    duration: 30,
    price: 700,
    description: 'Plaque and tartar inspection, gum health check, dental cleaning advice.',
    isActive: true,
  },

  // Dr. Emily Watson (Veterinarian - Pending)
  {
    providerEmail: 'dr.watson@petcare.com',
    name: 'Puppy Immunization',
    category: 'Veterinary',
    duration: 30,
    price: 900,
    description: 'Complete puppy starter vaccine course and deworming.',
    isActive: true,
  },
  {
    providerEmail: 'dr.watson@petcare.com',
    name: 'Kitten Health Screening',
    category: 'Veterinary',
    duration: 30,
    price: 650,
    description: 'Full viral check, ear mites inspection, and weight tracking.',
    isActive: true,
  },

  // Oliver Twist Grooming (Groomer)
  {
    providerEmail: 'oliver@petcare.com',
    name: 'Bath & Blow Dry',
    category: 'Grooming',
    duration: 45,
    price: 750,
    description: 'Hypoallergenic medicated bath, blow dry, ear cleaning, and paw pad balm.',
    isActive: true,
  },
  {
    providerEmail: 'oliver@petcare.com',
    name: 'Full Breed Grooming',
    category: 'Grooming',
    duration: 75,
    price: 1400,
    description: 'Complete haircut, shampoo, conditioning, nail clipping, and sanitary trim.',
    isActive: true,
  },
  {
    providerEmail: 'oliver@petcare.com',
    name: 'Nail Trimming & Buff',
    category: 'Grooming',
    duration: 20,
    price: 300,
    description: 'Stress-free claw trimming and smooth electric nail buffering.',
    isActive: true,
  },

  // Chloe Fluff Studio (Groomer)
  {
    providerEmail: 'chloe@petcare.com',
    name: 'Basic Grooming',
    category: 'Grooming',
    duration: 40,
    price: 650,
    description: 'Brushing, ear cleaning, nail trim, and refreshing pet cologne mist.',
    isActive: true,
  },
  {
    providerEmail: 'chloe@petcare.com',
    name: 'Spa Bath & Coat Conditioning',
    category: 'Grooming',
    duration: 50,
    price: 950,
    description: 'Aromatherapy bath, deep conditioning mask, and coat detangling.',
    isActive: true,
  },

  // Alex Canine Academy (Trainer)
  {
    providerEmail: 'alex@petcare.com',
    name: 'Basic Obedience',
    category: 'Training',
    duration: 60,
    price: 1200,
    description: 'Sit, stay, heel, recall, and impulse control techniques.',
    isActive: true,
  },
  {
    providerEmail: 'alex@petcare.com',
    name: 'Puppy Socialization',
    category: 'Training',
    duration: 60,
    price: 1000,
    description: 'Leash walking, environmental exposure, and anti-chewing conditioning.',
    isActive: true,
  },
  {
    providerEmail: 'alex@petcare.com',
    name: 'Behavior Correction',
    category: 'Training',
    duration: 90,
    price: 1800,
    description: 'Desensitization for aggression, separation anxiety, or excessive barking.',
    isActive: true,
  },

  // David Paws Training (Trainer - Suspended)
  {
    providerEmail: 'david@petcare.com',
    name: 'Guard Dog Basics',
    category: 'Training',
    duration: 60,
    price: 1500,
    description: 'Perimeter awareness and alert training for working breeds.',
    isActive: true,
  },
];

module.exports = {
  users,
  petsData,
  servicesData,
};
